FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    python3-dev \
    build-essential \
    libhdf5-dev \
    libhdf5-serial-dev \
    libatlas-base-dev \
    libblas-dev \
    liblapack-dev \
    gfortran \
    && apt-get clean

WORKDIR /app

COPY requirements.txt . 

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "app.py"]